"""Finalize pilot-20260721-1003 terminal summary.

Stamps ended_at, actual duration, and the verified dashboard rebuild record,
then validates the result against the prior slot's key layout so CLOSE_SUMMARY
can parse all of today's terminal files uniformly.

Pure local file rewrite. No network access. Invents no market value.
"""

import datetime
import json

P = "logs/launchd_worker/2026-07-21/pilot-20260721-1003.terminal.json"
REF = "logs/launchd_worker/2026-07-21/pilot-20260721-0943.terminal.json"

d = json.load(open(P, encoding="utf-8"))
now = datetime.datetime.now(datetime.timezone.utc)
d["ended_at"] = now.isoformat()
start = datetime.datetime.fromisoformat(d["started_at"])
d["timing"]["actual_duration_seconds"] = round((now - start).total_seconds(), 2)

d["dashboard_rebuild_status"] = "COMPLETED"
d["dashboard_rebuild_detail"] = {
    "builder": "scripts/build_shadow_dashboard.py",
    "output": "dashboard/index.html",
    "rebuilt_at": "2026-07-21T17:07:56.429545+00:00",
    "bytes": 44344,
    "exit_status": "OK",
    "verification": (
        "Output mtime confirmed as 17:07:56.4295Z against a verification clock "
        "reading of 17:07:56.4492Z, roughly 20 milliseconds later, so the file "
        "was genuinely regenerated by this run rather than left stale."
    ),
    "byte_size_note": (
        "44344 bytes, one byte larger than the 08:23 through 09:43 rebuilds at "
        "44343. The delta is a rendered-timestamp digit, not new content: ten "
        "consecutive NO_TRADE slots have added no trajectory events for the "
        "dashboard to display. Freshness was asserted from mtime, not size."
    ),
    "command_note": (
        "python3 main.py dashboard does not exist; main.py exposes no dashboard "
        "subcommand. The rebuild invokes scripts/build_shadow_dashboard.py "
        "directly, matching every prior slot today."
    ),
}

with open(P, "w", encoding="utf-8") as fh:
    json.dump(d, fh, indent=2, ensure_ascii=False)
    fh.write("\n")

d2 = json.load(open(P, encoding="utf-8"))
ref = json.load(open(REF, encoding="utf-8"))
print("json_valid OK")
print("duration_s", d2["timing"]["actual_duration_seconds"])
print("missing_vs_prior:", [k for k in ref if k not in d2])
print("extra_vs_prior:", [k for k in d2 if k not in ref])
print("eval_missing:", [k for k in ref["evaluation"] if k not in d2["evaluation"]])
print("labels:", list(d2["evaluation"]["labels"].keys()))
print("status", d2["status"], "| kind", d2["kind"], "| symbol", d2["symbol"])
